package zooog.jp.entity;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import zooog.jp.model.Login;
import zooog.jp.model.LoginExample;

public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    int countByExample(LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    int deleteByExample(LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    int insertSelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    List<Login> selectByExample(LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    Login selectByPrimaryKey(Integer id);

    /**Select user name*/
    Login selectByUserName(String user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    int updateByExampleSelective(@Param("record") Login record, @Param("example") LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    int updateByExample(@Param("record") Login record, @Param("example") LoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    int updateByPrimaryKeySelective(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    int updateByPrimaryKey(Login record);
}