package zooog.jp.entity;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import zooog.jp.model.Project;
import zooog.jp.model.ProjectExample;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    int countByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    int deleteByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    int deleteByPrimaryKey(String proposalnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    List<Project> selectByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    Project selectByPrimaryKey(String proposalnumber);

    /**
     * Select Project Name
     */
    Project selectByProjectTitle(String projecttitle);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    int updateByExampleSelective(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    int updateByExample(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    int updateByPrimaryKey(Project record);
}