package zooog.jp.model;

public class Login {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.user
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.pass
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    private String pass;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.user
     *
     * @return the value of login.user
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.user
     *
     * @param user the value for login.user
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.pass
     *
     * @return the value of login.pass
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    public String getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.pass
     *
     * @param pass the value for login.pass
     *
     * @mbggenerated Fri Mar 08 18:11:38 JST 2019
     */
    public void setPass(String pass) {
        this.pass = pass;
    }
}