package zooog.jp.model;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ProposalNumber
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    private String proposalnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ProjectTitle
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    private String projecttitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.MaxMonthly
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    private String maxmonthly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.NearestStation
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    private String neareststation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ApplicationTarget
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    private String applicationtarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ApplicationEndDate
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    private Date applicationenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.ProjectOverview
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    private String projectoverview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.Projectcol
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    private String projectcol;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ProposalNumber
     *
     * @return the value of project.ProposalNumber
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public String getProposalnumber() {
        return proposalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ProposalNumber
     *
     * @param proposalnumber the value for project.ProposalNumber
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void setProposalnumber(String proposalnumber) {
        this.proposalnumber = proposalnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ProjectTitle
     *
     * @return the value of project.ProjectTitle
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public String getProjecttitle() {
        return projecttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ProjectTitle
     *
     * @param projecttitle the value for project.ProjectTitle
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void setProjecttitle(String projecttitle) {
        this.projecttitle = projecttitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.MaxMonthly
     *
     * @return the value of project.MaxMonthly
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public String getMaxmonthly() {
        return maxmonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.MaxMonthly
     *
     * @param maxmonthly the value for project.MaxMonthly
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void setMaxmonthly(String maxmonthly) {
        this.maxmonthly = maxmonthly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.NearestStation
     *
     * @return the value of project.NearestStation
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public String getNeareststation() {
        return neareststation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.NearestStation
     *
     * @param neareststation the value for project.NearestStation
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void setNeareststation(String neareststation) {
        this.neareststation = neareststation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ApplicationTarget
     *
     * @return the value of project.ApplicationTarget
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public String getApplicationtarget() {
        return applicationtarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ApplicationTarget
     *
     * @param applicationtarget the value for project.ApplicationTarget
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void setApplicationtarget(String applicationtarget) {
        this.applicationtarget = applicationtarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ApplicationEndDate
     *
     * @return the value of project.ApplicationEndDate
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public Date getApplicationenddate() {
        return applicationenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ApplicationEndDate
     *
     * @param applicationenddate the value for project.ApplicationEndDate
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void setApplicationenddate(Date applicationenddate) {
        this.applicationenddate = applicationenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.ProjectOverview
     *
     * @return the value of project.ProjectOverview
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public String getProjectoverview() {
        return projectoverview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.ProjectOverview
     *
     * @param projectoverview the value for project.ProjectOverview
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void setProjectoverview(String projectoverview) {
        this.projectoverview = projectoverview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.Projectcol
     *
     * @return the value of project.Projectcol
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public String getProjectcol() {
        return projectcol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.Projectcol
     *
     * @param projectcol the value for project.Projectcol
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void setProjectcol(String projectcol) {
        this.projectcol = projectcol;
    }

	@Override
	public String toString() {
		return "Project [proposalnumber=" + proposalnumber + ", projecttitle=" + projecttitle + ", maxmonthly="
				+ maxmonthly + ", neareststation=" + neareststation + ", applicationtarget=" + applicationtarget
				+ ", applicationenddate=" + applicationenddate + ", projectoverview=" + projectoverview
				+ ", projectcol=" + projectcol + "]";
	}


}