package zooog.jp.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andProposalnumberIsNull() {
            addCriterion("ProposalNumber is null");
            return (Criteria) this;
        }

        public Criteria andProposalnumberIsNotNull() {
            addCriterion("ProposalNumber is not null");
            return (Criteria) this;
        }

        public Criteria andProposalnumberEqualTo(String value) {
            addCriterion("ProposalNumber =", value, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProposalnumberNotEqualTo(String value) {
            addCriterion("ProposalNumber <>", value, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProposalnumberGreaterThan(String value) {
            addCriterion("ProposalNumber >", value, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProposalnumberGreaterThanOrEqualTo(String value) {
            addCriterion("ProposalNumber >=", value, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProposalnumberLessThan(String value) {
            addCriterion("ProposalNumber <", value, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProposalnumberLessThanOrEqualTo(String value) {
            addCriterion("ProposalNumber <=", value, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProposalnumberLike(String value) {
            addCriterion("ProposalNumber like", value, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProposalnumberNotLike(String value) {
            addCriterion("ProposalNumber not like", value, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProposalnumberIn(List<String> values) {
            addCriterion("ProposalNumber in", values, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProposalnumberNotIn(List<String> values) {
            addCriterion("ProposalNumber not in", values, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProposalnumberBetween(String value1, String value2) {
            addCriterion("ProposalNumber between", value1, value2, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProposalnumberNotBetween(String value1, String value2) {
            addCriterion("ProposalNumber not between", value1, value2, "proposalnumber");
            return (Criteria) this;
        }

        public Criteria andProjecttitleIsNull() {
            addCriterion("ProjectTitle is null");
            return (Criteria) this;
        }

        public Criteria andProjecttitleIsNotNull() {
            addCriterion("ProjectTitle is not null");
            return (Criteria) this;
        }

        public Criteria andProjecttitleEqualTo(String value) {
            addCriterion("ProjectTitle =", value, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andProjecttitleNotEqualTo(String value) {
            addCriterion("ProjectTitle <>", value, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andProjecttitleGreaterThan(String value) {
            addCriterion("ProjectTitle >", value, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andProjecttitleGreaterThanOrEqualTo(String value) {
            addCriterion("ProjectTitle >=", value, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andProjecttitleLessThan(String value) {
            addCriterion("ProjectTitle <", value, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andProjecttitleLessThanOrEqualTo(String value) {
            addCriterion("ProjectTitle <=", value, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andProjecttitleLike(String value) {
            addCriterion("ProjectTitle like", value, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andProjecttitleNotLike(String value) {
            addCriterion("ProjectTitle not like", value, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andProjecttitleIn(List<String> values) {
            addCriterion("ProjectTitle in", values, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andProjecttitleNotIn(List<String> values) {
            addCriterion("ProjectTitle not in", values, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andProjecttitleBetween(String value1, String value2) {
            addCriterion("ProjectTitle between", value1, value2, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andProjecttitleNotBetween(String value1, String value2) {
            addCriterion("ProjectTitle not between", value1, value2, "projecttitle");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyIsNull() {
            addCriterion("MaxMonthly is null");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyIsNotNull() {
            addCriterion("MaxMonthly is not null");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyEqualTo(String value) {
            addCriterion("MaxMonthly =", value, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyNotEqualTo(String value) {
            addCriterion("MaxMonthly <>", value, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyGreaterThan(String value) {
            addCriterion("MaxMonthly >", value, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyGreaterThanOrEqualTo(String value) {
            addCriterion("MaxMonthly >=", value, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyLessThan(String value) {
            addCriterion("MaxMonthly <", value, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyLessThanOrEqualTo(String value) {
            addCriterion("MaxMonthly <=", value, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyLike(String value) {
            addCriterion("MaxMonthly like", value, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyNotLike(String value) {
            addCriterion("MaxMonthly not like", value, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyIn(List<String> values) {
            addCriterion("MaxMonthly in", values, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyNotIn(List<String> values) {
            addCriterion("MaxMonthly not in", values, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyBetween(String value1, String value2) {
            addCriterion("MaxMonthly between", value1, value2, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andMaxmonthlyNotBetween(String value1, String value2) {
            addCriterion("MaxMonthly not between", value1, value2, "maxmonthly");
            return (Criteria) this;
        }

        public Criteria andNeareststationIsNull() {
            addCriterion("NearestStation is null");
            return (Criteria) this;
        }

        public Criteria andNeareststationIsNotNull() {
            addCriterion("NearestStation is not null");
            return (Criteria) this;
        }

        public Criteria andNeareststationEqualTo(String value) {
            addCriterion("NearestStation =", value, "neareststation");
            return (Criteria) this;
        }

        public Criteria andNeareststationNotEqualTo(String value) {
            addCriterion("NearestStation <>", value, "neareststation");
            return (Criteria) this;
        }

        public Criteria andNeareststationGreaterThan(String value) {
            addCriterion("NearestStation >", value, "neareststation");
            return (Criteria) this;
        }

        public Criteria andNeareststationGreaterThanOrEqualTo(String value) {
            addCriterion("NearestStation >=", value, "neareststation");
            return (Criteria) this;
        }

        public Criteria andNeareststationLessThan(String value) {
            addCriterion("NearestStation <", value, "neareststation");
            return (Criteria) this;
        }

        public Criteria andNeareststationLessThanOrEqualTo(String value) {
            addCriterion("NearestStation <=", value, "neareststation");
            return (Criteria) this;
        }

        public Criteria andNeareststationLike(String value) {
            addCriterion("NearestStation like", value, "neareststation");
            return (Criteria) this;
        }

        public Criteria andNeareststationNotLike(String value) {
            addCriterion("NearestStation not like", value, "neareststation");
            return (Criteria) this;
        }

        public Criteria andNeareststationIn(List<String> values) {
            addCriterion("NearestStation in", values, "neareststation");
            return (Criteria) this;
        }

        public Criteria andNeareststationNotIn(List<String> values) {
            addCriterion("NearestStation not in", values, "neareststation");
            return (Criteria) this;
        }

        public Criteria andNeareststationBetween(String value1, String value2) {
            addCriterion("NearestStation between", value1, value2, "neareststation");
            return (Criteria) this;
        }

        public Criteria andNeareststationNotBetween(String value1, String value2) {
            addCriterion("NearestStation not between", value1, value2, "neareststation");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetIsNull() {
            addCriterion("ApplicationTarget is null");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetIsNotNull() {
            addCriterion("ApplicationTarget is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetEqualTo(String value) {
            addCriterion("ApplicationTarget =", value, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetNotEqualTo(String value) {
            addCriterion("ApplicationTarget <>", value, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetGreaterThan(String value) {
            addCriterion("ApplicationTarget >", value, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetGreaterThanOrEqualTo(String value) {
            addCriterion("ApplicationTarget >=", value, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetLessThan(String value) {
            addCriterion("ApplicationTarget <", value, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetLessThanOrEqualTo(String value) {
            addCriterion("ApplicationTarget <=", value, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetLike(String value) {
            addCriterion("ApplicationTarget like", value, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetNotLike(String value) {
            addCriterion("ApplicationTarget not like", value, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetIn(List<String> values) {
            addCriterion("ApplicationTarget in", values, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetNotIn(List<String> values) {
            addCriterion("ApplicationTarget not in", values, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetBetween(String value1, String value2) {
            addCriterion("ApplicationTarget between", value1, value2, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationtargetNotBetween(String value1, String value2) {
            addCriterion("ApplicationTarget not between", value1, value2, "applicationtarget");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateIsNull() {
            addCriterion("ApplicationEndDate is null");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateIsNotNull() {
            addCriterion("ApplicationEndDate is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateEqualTo(Date value) {
            addCriterionForJDBCDate("ApplicationEndDate =", value, "applicationenddate");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ApplicationEndDate <>", value, "applicationenddate");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateGreaterThan(Date value) {
            addCriterionForJDBCDate("ApplicationEndDate >", value, "applicationenddate");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ApplicationEndDate >=", value, "applicationenddate");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateLessThan(Date value) {
            addCriterionForJDBCDate("ApplicationEndDate <", value, "applicationenddate");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ApplicationEndDate <=", value, "applicationenddate");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateIn(List<Date> values) {
            addCriterionForJDBCDate("ApplicationEndDate in", values, "applicationenddate");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ApplicationEndDate not in", values, "applicationenddate");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ApplicationEndDate between", value1, value2, "applicationenddate");
            return (Criteria) this;
        }

        public Criteria andApplicationenddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ApplicationEndDate not between", value1, value2, "applicationenddate");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewIsNull() {
            addCriterion("ProjectOverview is null");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewIsNotNull() {
            addCriterion("ProjectOverview is not null");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewEqualTo(String value) {
            addCriterion("ProjectOverview =", value, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewNotEqualTo(String value) {
            addCriterion("ProjectOverview <>", value, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewGreaterThan(String value) {
            addCriterion("ProjectOverview >", value, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewGreaterThanOrEqualTo(String value) {
            addCriterion("ProjectOverview >=", value, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewLessThan(String value) {
            addCriterion("ProjectOverview <", value, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewLessThanOrEqualTo(String value) {
            addCriterion("ProjectOverview <=", value, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewLike(String value) {
            addCriterion("ProjectOverview like", value, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewNotLike(String value) {
            addCriterion("ProjectOverview not like", value, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewIn(List<String> values) {
            addCriterion("ProjectOverview in", values, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewNotIn(List<String> values) {
            addCriterion("ProjectOverview not in", values, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewBetween(String value1, String value2) {
            addCriterion("ProjectOverview between", value1, value2, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectoverviewNotBetween(String value1, String value2) {
            addCriterion("ProjectOverview not between", value1, value2, "projectoverview");
            return (Criteria) this;
        }

        public Criteria andProjectcolIsNull() {
            addCriterion("Projectcol is null");
            return (Criteria) this;
        }

        public Criteria andProjectcolIsNotNull() {
            addCriterion("Projectcol is not null");
            return (Criteria) this;
        }

        public Criteria andProjectcolEqualTo(String value) {
            addCriterion("Projectcol =", value, "projectcol");
            return (Criteria) this;
        }

        public Criteria andProjectcolNotEqualTo(String value) {
            addCriterion("Projectcol <>", value, "projectcol");
            return (Criteria) this;
        }

        public Criteria andProjectcolGreaterThan(String value) {
            addCriterion("Projectcol >", value, "projectcol");
            return (Criteria) this;
        }

        public Criteria andProjectcolGreaterThanOrEqualTo(String value) {
            addCriterion("Projectcol >=", value, "projectcol");
            return (Criteria) this;
        }

        public Criteria andProjectcolLessThan(String value) {
            addCriterion("Projectcol <", value, "projectcol");
            return (Criteria) this;
        }

        public Criteria andProjectcolLessThanOrEqualTo(String value) {
            addCriterion("Projectcol <=", value, "projectcol");
            return (Criteria) this;
        }

        public Criteria andProjectcolLike(String value) {
            addCriterion("Projectcol like", value, "projectcol");
            return (Criteria) this;
        }

        public Criteria andProjectcolNotLike(String value) {
            addCriterion("Projectcol not like", value, "projectcol");
            return (Criteria) this;
        }

        public Criteria andProjectcolIn(List<String> values) {
            addCriterion("Projectcol in", values, "projectcol");
            return (Criteria) this;
        }

        public Criteria andProjectcolNotIn(List<String> values) {
            addCriterion("Projectcol not in", values, "projectcol");
            return (Criteria) this;
        }

        public Criteria andProjectcolBetween(String value1, String value2) {
            addCriterion("Projectcol between", value1, value2, "projectcol");
            return (Criteria) this;
        }

        public Criteria andProjectcolNotBetween(String value1, String value2) {
            addCriterion("Projectcol not between", value1, value2, "projectcol");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbggenerated do_not_delete_during_merge Tue Aug 20 23:19:38 JST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbggenerated Tue Aug 20 23:19:38 JST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}