package zooog.jp.model;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.userID
     *
     * @mbggenerated Wed Mar 13 15:22:26 JST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.username
     *
     * @mbggenerated Wed Mar 13 15:22:26 JST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.password
     *
     * @mbggenerated Wed Mar 13 15:22:26 JST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.userID
     *
     * @return the value of test.userID
     *
     * @mbggenerated Wed Mar 13 15:22:26 JST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.userID
     *
     * @param userid the value for test.userID
     *
     * @mbggenerated Wed Mar 13 15:22:26 JST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.username
     *
     * @return the value of test.username
     *
     * @mbggenerated Wed Mar 13 15:22:26 JST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.username
     *
     * @param username the value for test.username
     *
     * @mbggenerated Wed Mar 13 15:22:26 JST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.password
     *
     * @return the value of test.password
     *
     * @mbggenerated Wed Mar 13 15:22:26 JST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.password
     *
     * @param password the value for test.password
     *
     * @mbggenerated Wed Mar 13 15:22:26 JST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }
}